#!/bin/bash
#SBATCH --qos=<QOS>
#SBATCH --time=<WALL>:00:00
#SBATCH --job-name=<JOBNAME>
#SBATCH --account=<GROUP>
#SBATCH --mail-user=<EMAIL>
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --output=./out.out
#SBATCH --error=./out.err

<OMPSECTION>

export GMON_OUT_PREFIX=./gmon

ulimit -s unlimited
#ulimit -c unlimited
#ulimit -s unlimited
#ulimit -d unlimited
#ulimit -m unlimited
ulimit -v unlimited
#ulimit -f unlimited
ulimit -a

# Run the job
srun <CMD> 
