#!/bin/bash
#SBATCH --qos=<QOS>
#SBATCH --partition=<PARTITION>
#SBATCH --time=<WALL>
#SBATCH --job-name=<JOBNAME>
#SBATCH --account=<ACCOUNT>
#SBATCH --output=./out.out
#SBATCH --error=./out.err
<EMAILSECTION>

<OMPSECTION>

ulimit -s unlimited
#ulimit -c unlimited
#ulimit -s unlimited
#ulimit -d unlimited
#ulimit -m unlimited
ulimit -v unlimited
#ulimit -f unlimited
ulimit -a

export GMON_OUT_PREFIX=./gmon
export LD_LIBRARY_PATH=${NETCDF_FORTRANROOT}/lib:${NETCDF_CROOT}/lib:$LD_LIBRARY_PATH
module load cdo

# Run the job
srun <CMD> 
